import { factories } from '@strapi/strapi'

// Cast to any so tsc accepts the UID before contentTypes.d.ts is regenerated by strapi build.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export default factories.createCoreRouter('api::consumable-product.consumable-product' as any)
