/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OylApp {
    }
}
declare global {
    interface HTMLOylAppElement extends Components.OylApp, HTMLStencilElement {
    }
    var HTMLOylAppElement: {
        prototype: HTMLOylAppElement;
        new (): HTMLOylAppElement;
    };
    interface HTMLElementTagNameMap {
        "oyl-app": HTMLOylAppElement;
    }
}
declare namespace LocalJSX {
    interface OylApp {
    }
    interface IntrinsicElements {
        "oyl-app": OylApp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "oyl-app": LocalJSX.IntrinsicElements["oyl-app"] & JSXBase.HTMLAttributes<HTMLOylAppElement>;
        }
    }
}
