export default [
  {
    question:
      "What is the legal blood alcohol concentration (BAC) limit for drivers 21 and older?",
    category: "Traffic Laws & General Rules",
    answer: "0.08%",
    wrongAnswers: ["0.05%", "0.10%", "0.15%", "0.02%"],
  },
  {
    question: "What is the BAC limit for drivers under 21?",
    category: "Traffic Laws & General Rules",
    answer: "0.01% (zero tolerance)",
    wrongAnswers: ["0.02%", "0.05%", "0.08%", "Same as adults (0.08%)"],
  },
  {
    question: "What does California's 'Basic Speed Law' state?",
    category: "Traffic Laws & General Rules",
    answer: "Never drive faster than safe for current conditions",
    wrongAnswers: [
      "Always drive at the posted speed limit",
      "Never exceed 65 mph on any road",
      "Match the speed of traffic around you",
      "Drive 5 mph below the speed limit in bad weather",
    ],
  },
  {
    question: "When must you report an accident to the DMV?",
    category: "Traffic Laws & General Rules",
    answer: "Within 10 days if damage exceeds $1,000 or injury/death occurred",
    wrongAnswers: [
      "Within 24 hours of any accident",
      "Within 30 days if damage exceeds $5,000",
      "Only if someone was killed",
      "Within 3 days if damage exceeds $500",
    ],
  },
  {
    question: "When is it illegal to use a cell phone while driving?",
    category: "Traffic Laws & General Rules",
    answer:
      "Without a hands-free device; completely banned for drivers under 18",
    wrongAnswers: [
      "Only when driving over 45 mph",
      "Only in school zones",
      "Never, cell phones are always allowed",
      "Only during nighttime hours",
    ],
  },
  {
    question: "What is the three-second rule?",
    category: "Traffic Laws & General Rules",
    answer: "Following distance to avoid tailgating",
    wrongAnswers: [
      "Time allowed to check mirrors",
      "Maximum time to complete a lane change",
      "Time to wait at a stop sign",
      "Signal duration before turning",
    ],
  },
  {
    question: "When can you drive in a bike lane?",
    category: "Traffic Laws & General Rules",
    answer:
      "Only when turning, entering/leaving the roadway, or parking where permitted",
    wrongAnswers: [
      "Whenever traffic is heavy",
      "To pass slower vehicles",
      "During rush hour only",
      "Never under any circumstances",
    ],
  },
  {
    question:
      "What is the speed limit in residential areas unless posted otherwise?",
    category: "Traffic Laws & General Rules",
    answer: "25 mph",
    wrongAnswers: ["15 mph", "30 mph", "35 mph", "20 mph"],
  },
  {
    question:
      "What is the speed limit near schools and senior centers when children or seniors are present?",
    category: "Traffic Laws & General Rules",
    answer: "25 mph",
    wrongAnswers: ["15 mph", "20 mph", "30 mph", "35 mph"],
  },
  {
    question: "What is the speed limit in business districts?",
    category: "Traffic Laws & General Rules",
    answer: "25 mph",
    wrongAnswers: ["30 mph", "35 mph", "20 mph", "40 mph"],
  },
  {
    question: "Who has the right-of-way at an uncontrolled intersection?",
    category: "Right-of-Way",
    answer: "Vehicle on the right",
    wrongAnswers: [
      "Vehicle on the left",
      "Larger vehicle",
      "Vehicle traveling faster",
      "Vehicle going straight",
    ],
  },
  {
    question: "Who must you yield to at all times?",
    category: "Right-of-Way",
    answer: "Pedestrians and emergency vehicles",
    wrongAnswers: [
      "Motorcycles only",
      "Larger vehicles",
      "Vehicles with more passengers",
      "Commercial vehicles",
    ],
  },
  {
    question: "When entering a roundabout, who has the right-of-way?",
    category: "Right-of-Way",
    answer: "Vehicles already in the roundabout",
    wrongAnswers: [
      "Vehicles entering from the right",
      "Vehicles entering from the left",
      "The first vehicle to arrive",
      "Larger vehicles",
    ],
  },
  {
    question: "At a four-way stop, who goes first?",
    category: "Right-of-Way",
    answer: "First to arrive; if simultaneous, vehicle on right",
    wrongAnswers: [
      "Vehicle on the left always goes first",
      "Largest vehicle goes first",
      "Vehicle going straight always goes first",
      "Vehicle traveling uphill goes first",
    ],
  },
  {
    question: "When making a left turn, who do you yield to?",
    category: "Right-of-Way",
    answer: "Oncoming traffic and pedestrians",
    wrongAnswers: [
      "Only vehicles turning right",
      "Only pedestrians",
      "Only oncoming traffic",
      "Vehicles behind you",
    ],
  },
  {
    question: "What shape is a stop sign?",
    category: "Traffic Signs",
    answer: "Octagon (8 sides)",
    wrongAnswers: ["Circle", "Triangle", "Square", "Pentagon"],
  },
  {
    question: "What color are warning signs?",
    category: "Traffic Signs",
    answer: "Yellow with black symbols",
    wrongAnswers: [
      "Red with white symbols",
      "Orange with black symbols",
      "White with black symbols",
      "Green with white symbols",
    ],
  },
  {
    question: "What do blue signs indicate?",
    category: "Traffic Signs",
    answer: "Motorist services",
    wrongAnswers: [
      "Construction zones",
      "Warning signs",
      "School zones",
      "No parking zones",
    ],
  },
  {
    question: "What do green signs indicate?",
    category: "Traffic Signs",
    answer: "Distance/direction information",
    wrongAnswers: [
      "Warning of hazards",
      "Construction zones",
      "Parking allowed",
      "Speed limits",
    ],
  },
  {
    question: "What do orange signs indicate?",
    category: "Traffic Signs",
    answer: "Construction/maintenance zones",
    wrongAnswers: [
      "School zones",
      "Parking regulations",
      "Motorist services",
      "Speed limit changes",
    ],
  },
  {
    question: "What does a yellow pentagon sign mean?",
    category: "Traffic Signs",
    answer: "School zone/crossing",
    wrongAnswers: [
      "Construction zone",
      "Hospital zone",
      "Railroad crossing",
      "Playground area",
    ],
  },
  {
    question: "What does a red triangle (inverted) sign mean?",
    category: "Traffic Signs",
    answer: "Yield",
    wrongAnswers: ["Stop", "Merge", "Slow down", "Caution"],
  },
  {
    question: "What does a red circle with a slash mean?",
    category: "Traffic Signs",
    answer: "Prohibited action",
    wrongAnswers: [
      "Yield required",
      "Caution ahead",
      "Construction zone",
      "Speed limit",
    ],
  },
  {
    question: "What does a diamond-shaped sign indicate?",
    category: "Traffic Signs",
    answer: "Warning",
    wrongAnswers: [
      "Regulatory information",
      "Construction zone",
      "School zone",
      "Motorist services",
    ],
  },
  {
    question: "What do regulatory signs look like?",
    category: "Traffic Signs",
    answer: "White with black/red markings",
    wrongAnswers: [
      "Yellow with black markings",
      "Orange with black markings",
      "Blue with white markings",
      "Green with white markings",
    ],
  },
  {
    question: "What does a red traffic light mean?",
    category: "Traffic Signals & Lights",
    answer: "Stop completely",
    wrongAnswers: [
      "Slow down and proceed with caution",
      "Yield to oncoming traffic",
      "Stop only if pedestrians are present",
      "Prepare to stop",
    ],
  },
  {
    question: "Can you turn right on a red light?",
    category: "Traffic Signals & Lights",
    answer: "Yes, after stopping and yielding, unless posted otherwise",
    wrongAnswers: [
      "No, never",
      "Yes, without stopping if clear",
      "Only during non-peak hours",
      "Only if no pedestrians are present",
    ],
  },
  {
    question: "Can you turn on a red arrow?",
    category: "Traffic Signals & Lights",
    answer: "No, never",
    wrongAnswers: [
      "Yes, after stopping",
      "Yes, if turning right only",
      "Yes, if no traffic is coming",
      "Yes, after yielding",
    ],
  },
  {
    question: "What does a yellow traffic light mean?",
    category: "Traffic Signals & Lights",
    answer: "Caution, light is about to turn red",
    wrongAnswers: [
      "Speed up to get through",
      "Stop immediately",
      "Yield to pedestrians only",
      "Slow down to 15 mph",
    ],
  },
  {
    question: "What does a flashing yellow light mean?",
    category: "Traffic Signals & Lights",
    answer: "Slow down and proceed with caution",
    wrongAnswers: [
      "Stop completely",
      "Speed limit reduced",
      "Yield to all traffic",
      "School zone active",
    ],
  },
  {
    question: "What does a flashing red light mean?",
    category: "Traffic Signals & Lights",
    answer: "Treat as a stop sign",
    wrongAnswers: [
      "Slow down and proceed with caution",
      "Stop only if traffic is present",
      "Emergency vehicles approaching",
      "Road closed ahead",
    ],
  },
  {
    question: "What does a green arrow mean?",
    category: "Traffic Signals & Lights",
    answer: "Protected turn, oncoming traffic is stopped",
    wrongAnswers: [
      "Yield before turning",
      "Proceed only if clear",
      "Advisory turn signal",
      "Turn only if no pedestrians present",
    ],
  },
  {
    question: "When must you dim your headlights for oncoming vehicles?",
    category: "Traffic Signals & Lights",
    answer: "Within 500 feet of oncoming vehicle",
    wrongAnswers: [
      "Within 1000 feet",
      "Within 200 feet",
      "Within 300 feet",
      "Only in residential areas",
    ],
  },
  {
    question: "When should you use low-beam headlights?",
    category: "Traffic Signals & Lights",
    answer: "In fog, rain, or when lights are required",
    wrongAnswers: [
      "Only at night",
      "Only in parking lots",
      "During daylight hours only",
      "Never, use high beams instead",
    ],
  },
  {
    question: "When should you use high beams?",
    category: "Traffic Signals & Lights",
    answer: "On open highways with no oncoming traffic",
    wrongAnswers: [
      "In fog for better visibility",
      "In city traffic",
      "When following other vehicles",
      "During rain storms",
    ],
  },
  {
    question: "What does a red curb mean?",
    category: "Parking",
    answer: "No stopping/parking",
    wrongAnswers: [
      "Fire lane only",
      "Loading zone",
      "15-minute parking",
      "Emergency vehicles only",
    ],
  },
  {
    question: "What does a white curb mean?",
    category: "Parking",
    answer: "Passenger loading/unloading only",
    wrongAnswers: [
      "No parking anytime",
      "Commercial vehicles only",
      "Disabled parking only",
      "5-minute parking",
    ],
  },
  {
    question: "What does a yellow curb mean?",
    category: "Parking",
    answer: "Commercial loading only",
    wrongAnswers: [
      "Caution area, parking allowed",
      "School zone parking",
      "15-minute parking",
      "Taxi stand only",
    ],
  },
  {
    question: "What does a blue curb mean?",
    category: "Parking",
    answer: "Disabled parking only with placard/plate",
    wrongAnswers: [
      "Police vehicles only",
      "Government vehicles only",
      "Carpool vehicles only",
      "Electric vehicle charging only",
    ],
  },
  {
    question: "What does a green curb mean?",
    category: "Parking",
    answer: "Limited time parking",
    wrongAnswers: [
      "Unlimited parking",
      "Eco-friendly vehicles only",
      "Motorcycle parking only",
      "Resident parking only",
    ],
  },
  {
    question: "How far from a fire hydrant must you park?",
    category: "Parking",
    answer: "15 feet",
    wrongAnswers: ["10 feet", "20 feet", "25 feet", "5 feet"],
  },
  {
    question: "How close to a railroad crossing can you park?",
    category: "Parking",
    answer: "No closer than 7.5 feet",
    wrongAnswers: [
      "No closer than 15 feet",
      "No closer than 25 feet",
      "No closer than 50 feet",
      "No closer than 100 feet",
    ],
  },
  {
    question: "How far from a crosswalk can you park?",
    category: "Parking",
    answer: "At least 20 feet",
    wrongAnswers: [
      "At least 10 feet",
      "At least 15 feet",
      "At least 25 feet",
      "At least 30 feet",
    ],
  },
  {
    question: "When parking uphill with a curb, which way do you turn wheels?",
    category: "Parking",
    answer: "Away from curb",
    wrongAnswers: [
      "Toward curb",
      "Straight ahead",
      "Depends on traffic direction",
      "Either direction is acceptable",
    ],
  },
  {
    question: "When parking downhill, which way do you turn wheels?",
    category: "Parking",
    answer: "Toward curb",
    wrongAnswers: [
      "Away from curb",
      "Straight ahead",
      "Depends on traffic direction",
      "Either direction is acceptable",
    ],
  },
  {
    question: "When changing lanes, what must you check?",
    category: "Lane Usage & Turning",
    answer: "Mirrors and blind spots by looking over shoulder",
    wrongAnswers: [
      "Only your mirrors",
      "Only your blind spots",
      "Only the rearview mirror",
      "Just signal and go",
    ],
  },
  {
    question: "How far in advance should you signal a turn?",
    category: "Lane Usage & Turning",
    answer: "At least 100 feet before turning",
    wrongAnswers: [
      "At least 50 feet",
      "At least 200 feet",
      "At least 25 feet",
      "Just before turning",
    ],
  },
  {
    question:
      "Which lane should you use for a left turn at a multi-lane intersection?",
    category: "Lane Usage & Turning",
    answer: "Left-most lane",
    wrongAnswers: [
      "Any lane is acceptable",
      "Center lane",
      "Right-most lane",
      "Second from left lane",
    ],
  },
  {
    question: "Can you pass on the right?",
    category: "Lane Usage & Turning",
    answer: "Only when safe and legal on multi-lane roads",
    wrongAnswers: [
      "Never",
      "Always",
      "Only on highways",
      "Only in emergencies",
    ],
  },
  {
    question: "What is a center left-turn lane used for?",
    category: "Lane Usage & Turning",
    answer: "Left turns only, not through traffic",
    wrongAnswers: [
      "Passing slower vehicles",
      "Through traffic during rush hour",
      "Emergency vehicles only",
      "U-turns only",
    ],
  },
  {
    question: "When entering a freeway, where should you signal?",
    category: "Lane Usage & Turning",
    answer: "On the entrance ramp before merging",
    wrongAnswers: [
      "After merging onto freeway",
      "Only if cars are nearby",
      "At the beginning of entrance ramp",
      "Signals not required on freeways",
    ],
  },
  {
    question: "When should you start reducing speed to exit a freeway?",
    category: "Lane Usage & Turning",
    answer: "Immediately upon entering deceleration lane",
    wrongAnswers: [
      "Halfway through the deceleration lane",
      "Before entering the deceleration lane",
      "After exiting the freeway",
      "At the approach to deceleration lane",
    ],
  },
  {
    question: "What does a solid white line mean?",
    category: "Lane Usage & Turning",
    answer: "Lane changes discouraged",
    wrongAnswers: [
      "Lane changes prohibited",
      "Lane changes required",
      "Parking lane boundary",
      "Emergency lane only",
    ],
  },
  {
    question: "What does a broken white line mean?",
    category: "Lane Usage & Turning",
    answer: "Lane changes permitted",
    wrongAnswers: [
      "Lane changes prohibited",
      "Lane ends ahead",
      "Caution area",
      "Merge required",
    ],
  },
  {
    question: "What do double solid yellow lines mean?",
    category: "Lane Usage & Turning",
    answer: "No passing in either direction",
    wrongAnswers: [
      "Passing allowed with caution",
      "Passing allowed from left side only",
      "Center turn lane",
      "Road divider only",
    ],
  },
  {
    question: "When is the road most slippery?",
    category: "Speed & Following Distance",
    answer: "First few minutes of rain on a hot day",
    wrongAnswers: [
      "After several hours of rain",
      "During heavy downpour",
      "When road is completely dry",
      "Just before rain starts",
    ],
  },
  {
    question: "How should you adjust speed in fog?",
    category: "Speed & Following Distance",
    answer: "Reduce speed and use low beams",
    wrongAnswers: [
      "Maintain speed and use high beams",
      "Increase speed to get through quickly",
      "Use hazard lights and maintain speed",
      "Stop on the roadway",
    ],
  },
  {
    question: "What should you do if your car hydroplanes?",
    category: "Speed & Following Distance",
    answer: "Ease off gas, don't brake suddenly",
    wrongAnswers: [
      "Brake hard immediately",
      "Accelerate to regain control",
      "Turn wheel sharply",
      "Shift into neutral",
    ],
  },
  {
    question: "How much space should you leave when following a motorcycle?",
    category: "Speed & Following Distance",
    answer: "Four seconds or more",
    wrongAnswers: [
      "Two seconds",
      "One second",
      "Three seconds",
      "Same as a car",
    ],
  },
  {
    question: "When should you increase following distance?",
    category: "Speed & Following Distance",
    answer: "Poor weather, heavy traffic, following large vehicles",
    wrongAnswers: [
      "Only in rain",
      "Only at night",
      "Only on highways",
      "Never necessary",
    ],
  },
  {
    question: "What should you do at a railroad crossing with flashing lights?",
    category: "Special Situations",
    answer: "Stop at least 15 feet from nearest rail",
    wrongAnswers: [
      "Stop at least 50 feet away",
      "Slow down and proceed if clear",
      "Stop at least 5 feet away",
      "Stop directly on the tracks",
    ],
  },
  {
    question: "What is the proper action when an emergency vehicle approaches?",
    category: "Special Situations",
    answer: "Pull to right and stop",
    wrongAnswers: [
      "Stop in your current lane",
      "Speed up to get out of way",
      "Pull to left and stop",
      "Continue at same speed",
    ],
  },
  {
    question:
      "What should you do if involved in an accident with a parked car and can't find the owner?",
    category: "Special Situations",
    answer: "Leave a note and report to police",
    wrongAnswers: [
      "Just leave the scene",
      "Wait 10 minutes then leave",
      "Only leave a note",
      "Only report to police",
    ],
  },
  {
    question: "When can you drive in a carpool lane?",
    category: "Special Situations",
    answer: "If you meet occupancy requirements during posted hours",
    wrongAnswers: [
      "Anytime if traffic is heavy",
      "Only with 3 or more occupants",
      "Only during rush hour",
      "Never, they are for buses only",
    ],
  },
  {
    question:
      "What must you do when a school bus displays flashing red lights?",
    category: "Special Situations",
    answer: "Stop in both directions unless divided highway",
    wrongAnswers: [
      "Slow down and proceed with caution",
      "Stop only if children are visible",
      "Stop only if you're behind the bus",
      "Stop only in school zones",
    ],
  },
  {
    question: "Where must you yield to pedestrians?",
    category: "Pedestrians & Bicycles",
    answer: "Crosswalks, marked or unmarked",
    wrongAnswers: [
      "Only at marked crosswalks",
      "Only when traffic light is red",
      "Only in school zones",
      "Only at intersections",
    ],
  },
  {
    question: "Can pedestrians cross outside a crosswalk?",
    category: "Pedestrians & Bicycles",
    answer: "Yes, but must yield to vehicles",
    wrongAnswers: [
      "No, never",
      "Yes, and vehicles must yield",
      "Only in residential areas",
      "Only during daylight",
    ],
  },
  {
    question: "How much space must you give a bicycle when passing?",
    category: "Pedestrians & Bicycles",
    answer: "At least 3 feet",
    wrongAnswers: [
      "At least 5 feet",
      "At least 2 feet",
      "At least 6 feet",
      "At least 1 foot",
    ],
  },
  {
    question: "When can bicyclists use the full lane?",
    category: "Pedestrians & Bicycles",
    answer: "When lane is too narrow to share safely",
    wrongAnswers: [
      "Never",
      "Only on residential streets",
      "Only during rush hour",
      "Anytime they want",
    ],
  },
  {
    question: "What must you do before opening your car door?",
    category: "Pedestrians & Bicycles",
    answer: "Check for cyclists and pedestrians",
    wrongAnswers: [
      "Sound your horn",
      "Turn on hazard lights",
      "Nothing special required",
      "Only check mirrors",
    ],
  },
  {
    question: "How does fatigue affect driving?",
    category: "Impaired & Distracted Driving",
    answer: "Affects vision and increases reaction time",
    wrongAnswers: [
      "Only affects reaction time",
      "Only affects vision",
      "Has no significant effect",
      "Only affects judgment",
    ],
  },
  {
    question: "What medications can impair driving?",
    category: "Impaired & Distracted Driving",
    answer: "Any that cause drowsiness or affect judgment",
    wrongAnswers: [
      "Only prescription medications",
      "Only illegal drugs",
      "Only pain medications",
      "Medications don't affect driving",
    ],
  },
  {
    question: "Is it legal to drive while wearing headphones?",
    category: "Impaired & Distracted Driving",
    answer: "Only one ear can be covered",
    wrongAnswers: [
      "No, never",
      "Yes, both ears allowed",
      "Only with noise-canceling headphones",
      "Only on highways",
    ],
  },
  {
    question: "What is the penalty for a DUI?",
    category: "Impaired & Distracted Driving",
    answer: "License suspension, fines, possible jail time",
    wrongAnswers: [
      "Only a fine",
      "Only license suspension",
      "Only traffic school",
      "Warning for first offense",
    ],
  },
  {
    question: "Can you refuse a chemical test?",
    category: "Impaired & Distracted Driving",
    answer: "Yes, but automatic license suspension",
    wrongAnswers: [
      "No, refusal is illegal",
      "Yes, with no consequences",
      "Only if you have an attorney present",
      "Only during first offense",
    ],
  },
  {
    question: "At what age can you apply for a learner's permit?",
    category: "License & Permit Requirements",
    answer: "15½ years old",
    wrongAnswers: [
      "15 years old",
      "16 years old",
      "14½ years old",
      "17 years old",
    ],
  },
  {
    question:
      "How long must you hold a permit before taking the driving test if under 18?",
    category: "License & Permit Requirements",
    answer: "6 months",
    wrongAnswers: ["3 months", "12 months", "9 months", "1 month"],
  },
  {
    question: "How many hours of supervised driving are required for minors?",
    category: "License & Permit Requirements",
    answer: "50 hours, including 10 at night",
    wrongAnswers: [
      "40 hours, including 10 at night",
      "60 hours, including 15 at night",
      "30 hours, including 5 at night",
      "100 hours, including 20 at night",
    ],
  },
  {
    question: "What are the driving hours for permit holders under 18?",
    category: "License & Permit Requirements",
    answer: "5 AM to 11 PM only",
    wrongAnswers: [
      "6 AM to 10 PM only",
      "Anytime with supervision",
      "7 AM to 9 PM only",
      "Daylight hours only",
    ],
  },
  {
    question: "Who can supervise a minor permit holder?",
    category: "License & Permit Requirements",
    answer: "Licensed driver 25+ in front passenger seat",
    wrongAnswers: [
      "Any licensed driver 18+",
      "Parent or guardian only",
      "Licensed driver 21+ in any seat",
      "Certified instructor only",
    ],
  },
  {
    question: "What is the proper hand position on the steering wheel?",
    category: "Defensive Driving",
    answer: "9 and 3 o'clock",
    wrongAnswers: [
      "10 and 2 o'clock",
      "8 and 4 o'clock",
      "12 o'clock with one hand",
      "Bottom of wheel",
    ],
  },
  {
    question: "When should you use hand-over-hand steering?",
    category: "Defensive Driving",
    answer: "Low-speed turns, parking, recovering from skids",
    wrongAnswers: [
      "Highway driving",
      "Only during emergencies",
      "Lane changes",
      "Never recommended",
    ],
  },
  {
    question: "Where should you look when driving?",
    category: "Defensive Driving",
    answer: "10-15 seconds ahead",
    wrongAnswers: [
      "Directly in front of your hood",
      "5 seconds ahead",
      "20-25 seconds ahead",
      "Only at the car ahead",
    ],
  },
  {
    question: "How often should you check mirrors?",
    category: "Defensive Driving",
    answer: "Every 5-8 seconds",
    wrongAnswers: [
      "Every 10-15 seconds",
      "Only when changing lanes",
      "Every 2-3 seconds",
      "Once per minute",
    ],
  },
  {
    question: "How do you handle a tire blowout?",
    category: "Defensive Driving",
    answer: "Grip wheel firmly, ease off gas, don't brake suddenly",
    wrongAnswers: [
      "Brake hard immediately",
      "Accelerate to maintain control",
      "Turn wheel sharply",
      "Pull emergency brake",
    ],
  },
  {
    question: "What vehicles must stop at all railroad crossings?",
    category: "Special Vehicles & Conditions",
    answer: "School buses, hazardous material trucks",
    wrongAnswers: [
      "All vehicles",
      "Only school buses",
      "Only commercial trucks",
      "Only buses",
    ],
  },
  {
    question: "How should you pass a large truck?",
    category: "Special Vehicles & Conditions",
    answer: "Ensure you can see driver in mirror, signal, pass quickly",
    wrongAnswers: [
      "Stay in blind spot until clear",
      "Pass slowly on the right",
      "Flash lights before passing",
      "Pass only on left with 10-second gap",
    ],
  },
  {
    question: "What is a truck's blind spot called?",
    category: "Special Vehicles & Conditions",
    answer: "No-zone",
    wrongAnswers: ["Dead zone", "Blind area", "Danger zone", "Shadow zone"],
  },
  {
    question: "How do motorcycles use lanes?",
    category: "Special Vehicles & Conditions",
    answer: "Entitled to full lane width",
    wrongAnswers: [
      "Must share lane with cars",
      "Can only use right portion",
      "Must stay in center",
      "Can use bike lanes",
    ],
  },
  {
    question: "When is road rage most dangerous?",
    category: "Special Vehicles & Conditions",
    answer: "When it leads to aggressive driving or confrontation",
    wrongAnswers: [
      "Only in parking lots",
      "Only on highways",
      "Only during rush hour",
      "It's never actually dangerous",
    ],
  },
  {
    question: "What should you do to conserve fuel?",
    category: "Environmental & Safe Driving",
    answer: "Maintain steady speed, avoid rapid acceleration",
    wrongAnswers: [
      "Drive faster to reduce time",
      "Brake frequently",
      "Use high gears at low speeds",
      "Keep windows open on highway",
    ],
  },
  {
    question: "How does tire pressure affect driving?",
    category: "Environmental & Safe Driving",
    answer: "Under-inflation reduces control and fuel economy",
    wrongAnswers: [
      "Tire pressure doesn't affect driving",
      "Over-inflation improves handling",
      "Only affects comfort",
      "Only matters for long trips",
    ],
  },
  {
    question: "When should you check your vehicle before driving?",
    category: "Environmental & Safe Driving",
    answer: "Every time, pre-drive check",
    wrongAnswers: [
      "Once a week",
      "Only for long trips",
      "Once a month",
      "Only when warning lights appear",
    ],
  },
  {
    question: "What documents must you carry while driving?",
    category: "Environmental & Safe Driving",
    answer: "License, registration, proof of insurance",
    wrongAnswers: [
      "Only license",
      "License and registration only",
      "License and insurance only",
      "Registration only",
    ],
  },
  {
    question: "How often should you check your blind spots?",
    category: "Environmental & Safe Driving",
    answer: "Every lane change and merge",
    wrongAnswers: [
      "Only on highways",
      "Once every 5 minutes",
      "Only when turning",
      "Only in heavy traffic",
    ],
  },
  {
    question: "What does 'scanning' mean in driving?",
    category: "Final Critical Concepts",
    answer: "Constantly checking road, mirrors, and surroundings",
    wrongAnswers: [
      "Looking for parking spots",
      "Watching for police",
      "Reading road signs",
      "Checking speedometer",
    ],
  },
  {
    question: "What is the safest thing to do if you miss your exit?",
    category: "Final Critical Concepts",
    answer: "Continue to next exit",
    wrongAnswers: [
      "Back up on the shoulder",
      "Stop and reverse",
      "Make a U-turn",
      "Cross multiple lanes quickly",
    ],
  },
  {
    question: "When are California roads most congested?",
    category: "Final Critical Concepts",
    answer: "Weekday rush hours: 6-9 AM and 3-7 PM",
    wrongAnswers: [
      "Weekends all day",
      "Late night hours",
      "Weekday midday only",
      "Sunday mornings",
    ],
  },
  {
    question: "What should you do if your brakes fail?",
    category: "Final Critical Concepts",
    answer: "Pump brakes, downshift, use emergency brake gradually",
    wrongAnswers: [
      "Pull emergency brake hard immediately",
      "Turn off engine",
      "Swerve to shoulder immediately",
      "Honk horn continuously",
    ],
  },
  {
    question: "What is the most common cause of accidents?",
    category: "Final Critical Concepts",
    answer: "Speeding and following too closely",
    wrongAnswers: [
      "Mechanical failure",
      "Weather conditions",
      "Poor road conditions",
      "Night driving",
    ],
  },
];
