// The only barrel — and (in later phases) the only file allowed to know
// every module, which is why the kind→fromJSON revivers will live here.

export { DomainError, type DomainErrorCode } from './core/domain-error'
export { assertSlug, isSlug } from './core/slug'
export { Id } from './core/id'
export { KNOWN_NAMESPACES, MEASUREMENT_NAMESPACES, MetricKey } from './core/metric-key'
export { DayKey, assertTimezone } from './core/day-key'
export { DayRange } from './core/day-range'
export { Cadence, type CadenceUnit } from './core/cadence'
export { Quantity } from './core/quantity'
export { Money } from './core/money'
export { type PersistedMeta, type PersistedMetaShape, metaFromJSON, metaToJSON } from './core/persisted-meta'
export { LifeArea } from './core/life-area'
export { Entry } from './core/entry'
export { Plan, type PlanStatus } from './core/plan'
export { Journal, type AggregateKind } from './core/journal'
export { Catalog } from './core/catalog'
export { type Repository } from './core/repository'
export { InMemoryRepository } from './core/in-memory-repository'
export { User, type Units } from './user/user'
export { fixtureId } from './fixtures/fixture-id'
export { FIXTURE_TODAY, FIXTURE_TZ } from './fixtures/constants'
export { makeLifeArea, makeUser } from './fixtures/builders'
export { seed } from './fixtures/seed'
