/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IconName } from "./components/ui-icon/icons.js";
export { IconName } from "./components/ui-icon/icons.js";
export namespace Components {
    /**
     * Inline SVG icon from the library's small glyph map. Decorative unless `label` is set.
     */
    interface UiIcon {
        /**
          * Accessible name; when set the icon is announced, otherwise it is hidden from AT.
         */
        "label"?: string;
        /**
          * Glyph name (see `ICON_NAMES`). Unknown names render nothing.
         */
        "name": IconName;
        /**
          * `s` = 16px, `m` = 20px.
          * @default 'm'
         */
        "size": 's' | 'm';
    }
}
declare global {
    /**
     * Inline SVG icon from the library's small glyph map. Decorative unless `label` is set.
     */
    interface HTMLUiIconElement extends Components.UiIcon, HTMLStencilElement {
    }
    var HTMLUiIconElement: {
        prototype: HTMLUiIconElement;
        new (): HTMLUiIconElement;
    };
    interface HTMLElementTagNameMap {
        "ui-icon": HTMLUiIconElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K]?: never };

    /**
     * Inline SVG icon from the library's small glyph map. Decorative unless `label` is set.
     */
    interface UiIcon {
        /**
          * Accessible name; when set the icon is announced, otherwise it is hidden from AT.
         */
        "label"?: string;
        /**
          * Glyph name (see `ICON_NAMES`). Unknown names render nothing.
         */
        "name": IconName;
        /**
          * `s` = 16px, `m` = 20px.
          * @default 'm'
         */
        "size"?: 's' | 'm';
    }

    interface UiIconAttributes {
        "name": IconName;
        "size": 's' | 'm';
        "label": string;
    }

    interface IntrinsicElements {
        "ui-icon": Omit<UiIcon, keyof UiIconAttributes> & { [K in keyof UiIcon & keyof UiIconAttributes]?: UiIcon[K] } & { [K in keyof UiIcon & keyof UiIconAttributes as `attr:${K}`]?: UiIconAttributes[K] } & { [K in keyof UiIcon & keyof UiIconAttributes as `prop:${K}`]?: UiIcon[K] } & OneOf<"name", UiIcon["name"], UiIconAttributes["name"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Inline SVG icon from the library's small glyph map. Decorative unless `label` is set.
             */
            "ui-icon": LocalJSX.IntrinsicElements["ui-icon"] & JSXBase.HTMLAttributes<HTMLUiIconElement>;
        }
    }
}
